name: Deploy Lab 3

on:
  push:
    branches: [ master, feature ]

jobs:
  lint-html:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Lint HTML
        uses: Cyb3r-Jak3/html5validator-action@v7.2.0
        with:
          root: ./

  docker-build:
    runs-on: ubuntu-latest
    needs: lint-html
    steps:
      - uses: actions/checkout@v3
      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/si-2025-lab3:master-latest .
          docker images | grep si-2025-lab3

  docker-push:
    runs-on: ubuntu-latest
    needs: docker-build
    steps:
      - name: Push Docker image to DockerHub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/si-2025-lab3:master-latest

  github-pages:
    if: github.ref_name == 'master'
    runs-on: ubuntu-latest
    needs: docker-push
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
